### ISSUE TITLE
类型错误："__VITE_PRELOAD__".map 不是一个 function

### ISSUE THREAD

**Issue by Bisstocuz** [imzbf/md-editor-v3#363]
### 描述这个Bug

这个问题很诡异，我在本地 pnpm build && pnpm preview 没有任何问题，但一构建完 push 到线上服务器通过浏览器直接访问就在控制台抛下面的错误：
```
TypeError: n.map is not a function
    at Ff (runtime-b1db766b.js:5:659)
    at md-editor-98e4c02e.js:2:3722
    at runtime-b1db766b.js:1:24664
    at ot (runtime-b1db766b.js:1:14161)
    at Re (runtime-b1db766b.js:1:14239)
    at Kn.t.__weh.t.__weh (runtime-b1db766b.js:1:24544)
    at qo (runtime-b1db766b.js:1:15532)
    at zo (runtime-b1db766b.js:1:15839)

TypeError: n.map is not a function
    at Ff (runtime-b1db766b.js:5:659)
    at md-editor-98e4c02e.js:2:3722
    at runtime-b1db766b.js:1:24664
    at ot (runtime-b1db766b.js:1:14161)
    at Re (runtime-b1db766b.js:1:14239)
    at Kn.t.__weh.t.__weh (runtime-b1db766b.js:1:24544)
    at qo (runtime-b1db766b.js:1:15532)
    at zo (runtime-b1db766b.js:1:15839)
```

问题堆栈代码段 1（`runtime-b1db766b.js:5:659`）：
出问题的代码行是 `return Promise.all(n.map(o=>{`
```javascript
/*!
  * pinia v2.1.4
  * (c) 2023 Eduardo San Martin Morote
  * @license MIT
  */
const Ou = Symbol();
var Vs;
(function(e) {
    e.direct = "direct",
    e.patchObject = "patch object",
    e.patchFunction = "patch function"
}
)(Vs || (Vs = {}));
function Mf() {
    const e = ol(!0)
      , t = e.run(()=>Fe({}));
    let n = []
      , r = [];
    const s = Lr({
        install(o) {
            s._a = o,
            o.provide(Ou, s),
            o.config.globalProperties.$pinia = s,
            r.forEach(i=>n.push(i)),
            r = []
        },
        use(o) {
            return !this._a && !Pu ? r.push(o) : n.push(o),
            this
        },
        _p: n,
        _a: null,
        _e: e,
        _s: new Map,
        state: t
    });
    return s
}
const Nf = (e,t)=>{
    const n = e.__vccOpts || e;
    for (const [r,s] of t)
        n[r] = s;
    return n
}
  , Ru = "modulepreload"
  , Tu = function(e) {
    return "/" + e
}
  , Ws = {}
  , Ff = function(t, n, r) {
    if (!n || n.length === 0)
        return t();
    const s = document.getElementsByTagName("link");
    return Promise.all(n.map(o=>{
        if (o = Tu(o),
        o in Ws)
            return;
        Ws[o] = !0;
        const i = o.endsWith(".css")
          , l = i ? '[rel="stylesheet"]' : "";
        if (!!r)
            for (let a = s.length - 1; a >= 0; a--) {
                const p = s[a];
                if (p.href === o && (!i || p.rel === "stylesheet"))
                    return
            }
        else if (document.querySelector(`link[href="${o}"]${l}`))
            return;
        const u = document.createElement("link");
        if (u.rel = i ? "stylesheet" : Ru,
        i || (u.as = "script",
        u.crossOrigin = ""),
        u.href = o,
        document.head.appendChild(u),
        i)
            return new Promise((a,p)=>{
                u.addEventListener("load", a),
                u.addEventListener("error", ()=>p(new Error(`Unable to preload CSS for ${o}`)))
            }
            )
    }
    )).then(()=>t()).catch(o=>{
        const i = new Event("vite:preloadError",{
            cancelable: !0
        });
        if (i.payload = o,
        window.dispatchEvent(i),
        !i.defaultPrevented)
            throw o
    }
    )
};
```
问题堆栈代码段 2（`md-editor-98e4c02e.js:2:3722`）：
出问题的代码行是 `At(()=>import(h), "__VITE_PRELOAD__").then(s=>{`
```javascript
    M(()=>{
        if (!e.noMermaid && !(o != null && o.instance)) {
            const h = (o == null ? void 0 : o.js) || ll;
            if (/\.mjs/.test(h))
                At(()=>import(h), "__VITE_PRELOAD__").then(s=>{
                    n.value = s.default,
                    u()
                }
                );
            else {
                const s = document.createElement("script");
                s.id = `${d}-mermaid`,
                s.src = h,
                s.onload = ()=>{
                    n.value = window.mermaid,
                    u()
                }
                ,
                K(s, "mermaid")
            }
        }
    }
    ),
```

### 版本号

Microsoft Edge 117.0.2045.31

package.json:
```json
  "dependencies": {
    "@element-plus/icons-vue": "^2.1.0",
    "axios": "^1.5.0",
    "element-plus": "^2.3.14",
    "lodash-es": "^4.17.21",
    "md-editor-v3": "^4.6.2",
    "pinia": "^2.1.6",
    "sass": "^1.63.6",
    "spark-md5": "^3.0.2",
    "vue": "^3.3.4",
    "vue-hooks-plus": "^1.8.2",
    "vue-router": "^4.2.0"
  },
  "devDependencies": {
    "@iconify-json/ep": "^1.1.11",
    "@rushstack/eslint-patch": "^1.2.0",
    "@tsconfig/node-lts": "^18.12.5",
    "@types/lodash-es": "^4.17.9",
    "@types/node": "^18.16.8",
    "@types/spark-md5": "^3.0.2",
    "@vitejs/plugin-vue": "^4.3.4",
    "@vitejs/plugin-vue-jsx": "^3.0.2",
    "@vue/eslint-config-prettier": "^7.1.0",
    "@vue/eslint-config-typescript": "^11.0.3",
    "@vue/tsconfig": "^0.4.0",
    "eslint": "^8.45.0",
    "eslint-plugin-vue": "^9.15.1",
    "npm-run-all": "^4.1.5",
    "prettier": "^2.8.8",
    "sass": "^1.63.6",
    "typescript": "~5.0.4",
    "unplugin-auto-import": "^0.16.6",
    "unplugin-icons": "^0.16.3",
    "unplugin-vue-components": "^0.25.1",
    "vite": "^4.4.9",
    "vite-plugin-compression2": "^0.10.4",
    "vite-plugin-dynamic-import": "^1.5.0",
    "vue-tsc": "^1.8.11"
  }
```

**Comment by Bisstocuz** [comment]
看起来像是 `At` 调用时没有传 `Ff = function(t, n, r)` 的第二个参数 `n` 导致的。

**Comment by Bisstocuz** [comment]
应该对应这段代码：
```javascript
  onMounted(() => {
    if (props.noMermaid) {
      return;
    }

    // 没有提供实例，引入mermaid
    if (!mermaidConf?.instance) {
      const jsSrc = mermaidConf?.js || mermaidUrl;

      if (/\.mjs/.test(jsSrc)) {
        import(
          /* @vite-ignore */
          /* webpackIgnore: true */
          jsSrc
        ).then((module) => {
          mermaidRef.value = module.default;
          setMermaidTheme();
        });
      } else {
        const mermaidScript = document.createElement('script');
        mermaidScript.id = `${prefix}-mermaid`;
        mermaidScript.src = jsSrc;

        mermaidScript.onload = () => {
          mermaidRef.value = window.mermaid;
          setMermaidTheme();
        };

        appendHandler(mermaidScript, 'mermaid');
      }
    }
  });
```
🤣看起来有点像是我的用法问题。

**Comment by Bisstocuz** [comment]
构建输出的文件：
```javascript
      M(() => {
        if (!e.noMermaid && !(o != null && o.instance)) {
          const p = (o == null ? void 0 : o.js) || Ul;
          if (/\.mjs/.test(p))
            kl(() => import(p), []).then((r) => {
              (n.value = r.default), u();
            });
          else {
            const r = document.createElement("script");
            (r.id = `${c}-mermaid`),
              (r.src = p),
              (r.onload = () => {
                (n.value = window.mermaid), u();
              }),
              G(r, "mermaid");
          }
        }
      }),
```

它的表现就是输出的文件是正确的，我直接用 VSCode 打开这里是一个 `[]`，并且使用 `vite preview` 也是正常工作的，浏览器开发者工具查看这里的参数也是 `[]`，但是一旦放到线上使用 nginx 提供服务，到了浏览器里就变成了 "__VITE_PRELOAD__"。

看起来相关的工单：
- https://github.com/vitejs/vite/issues/3051

**Comment by imzbf** [comment]
具体的情况需要再尝试看看

这个组件有一个办法可以规避执行这段代码，就是通过在你的项目中安装`mermaid`，然后将实例配置到组件中，动态引入的代码就不会执行。希望这可以临时解决你的问题

```
yarn add mermaid
```

```
import { config } from 'md-editor-v3';
import mermaid from 'mermaid';

config({
  editorExtensions: {
    mermaid: {
      instance: mermaid
    }
  }
});
```
